use_frameworks!

platform :ios, '10.0'

target 'TronWalletKeystore_Example' do
  pod 'TronWalletKeystore', :path => '../'

  target 'TronWalletKeystore_Tests' do
    inherit! :search_paths

    
  end
end
